### PR TITLE
Uptade to 2021.6.5

### PR DESCRIPTION
**Pull request by ewilly**

### CODE REVIEW

**Comment by ewilly** [comment]
!testme

**Comment by alexAubin** [comment]
Hm that's a bit odd, backup/restore complains with this weird issue about the port being already used: 

```
23325 INFO [##++................] > Restoring the port and opening it...
23493 WARNING 8123 is not available, please use an other port
```

**Comment by ewilly** [comment]
!testme

**Comment by ewilly** [comment]
> Hm that's a bit odd, backup/restore complains with this weird issue about the port being already used:
> 
> ```
> 23325 INFO [##++................] > Restoring the port and opening it...
> 23493 WARNING 8123 is not available, please use an other port
> ```

can't understand why it failed... expected a ci bug... try a new test

**Comment by ewilly** [comment]
!testme

**Pull request merged**
