### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ewilly**

### CODE REVIEW

**Comment by ewilly** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
@ewilly What do you think about silencing the numerous warnings during Python compilation with `ynh_exec_warn_less` ?

**Comment by ewilly** [comment]
@tituspijean : yes they are more annoying than usefull...

**Comment by tituspijean** [comment]
Done! My VM has the wrong time... the commit has been put higher in the thread.

**Comment by ewilly** [comment]
perhaps we filter too much by adding `ynh_exec_warn_less` in front of `myynh_install_dependencies`, would not be better to simply add it on front of `make -j4` and `make altinstall`...
@tituspijean : whats your opinion ?

**Comment by ewilly** [comment]
!testme

**Pull request merged**
